apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
name: jx3-gohttp-gs2
version: 0.0.1
